permalink: /:categories/:year/:title/
markdown: kramdown
highlighter: rouge
paginate: 2
paginate_path: "/page/:num"

destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: zzl3141的博客
description: "我的个人博客"
email: 2212058406@qq.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zzl3141.github.io"
repository: "https://github.com/zzl3141/zzl3141.github.io"
comments: false

# social footer
social:
  github:
    slug: github
    link: https://github.com/zzl3141